name: Update daily

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
jobs:
  alter_repo:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Git configuration
        run: |
          git config --global user.email "tilmangmelin@gmx.de"
          git config --global user.name "Tilman Gmelin"

      - name: Extract target number of commits from seed.txt
        id: extract_seed
        run: |
          NUMBER=$(grep $(date +%F) seed.txt | cut -d' ' -f2)
          echo "TARGET_COMMITS=$NUMBER" >> $GITHUB_ENV

      - name: Fetch commits from GitHub activity
        id: fetch_activity
        env:
          SENIOR_TOKEN: ${{ secrets.SENIOR_TOKEN }}
        run: |
          # Get the authenticated user's username
          echo "Authenticating"
          gh auth login --with-token <<< "$SENIOR_TOKEN"
          USERNAME=$(gh api user --jq .login)
          echo "Authenticated as $USERNAME"

          TODAY=$(date +%Y-%m-%d)
          COMMIT_COUNT=$(gh api "/users/$USERNAME/events" | jq --arg today "$TODAY" '
            map(select(.type == "PushEvent" and .created_at[:10] == $today)) 
            | map(.payload.commits) | flatten | length
          ')
          
          echo "COMMIT_COUNT=$COMMIT_COUNT" >> $GITHUB_ENV
          echo "Found $COMMIT_COUNT commits today"
          
      - name: Create missing commits
        id: create_missing
        env:
          TARGET_COMMITS: ${{ env.TARGET_COMMITS }}
          COMMIT_COUNT: ${{ env.COMMIT_COUNT }}
          SENIOR_TOKEN: ${{ secrets.SENIOR_TOKEN }}
        run: |
          for ((i = $COMMIT_COUNT; i < $TARGET_COMMITS; i++)); do
            random_string=$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 5)
            new_line="[${random_string}] All work and no play make jack a dull boy!"
            echo "$new_line" >> book.txt
            git add book.txt && git commit -m "$new_line"
          done
          git push https://x-access-token:$SENIOR_TOKEN@github.com/${{ github.repository }}.git
